// <auto-generated />
using System;
using EfCoreShop.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EfCoreShop.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20211223170020_1")]
    partial class _1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EfCoreShop.Models.Shop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Shops");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Minima"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Media"
                        });
                });

            modelBuilder.Entity("EfCoreShop.Models.ShopItemTag", b =>
                {
                    b.Property<int>("TagId")
                        .HasColumnType("int");

                    b.Property<int>("ShopItemId")
                        .HasColumnType("int");

                    b.HasKey("TagId", "ShopItemId");

                    b.HasIndex("ShopItemId");

                    b.ToTable("ShopItemTags");
                });

            modelBuilder.Entity("EfCoreShop.Models.Shopitem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("ShopId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ShopId");

                    b.ToTable("Shopitems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ExpiryDate = new DateTime(2021, 12, 23, 17, 0, 20, 306, DateTimeKind.Utc).AddTicks(7471),
                            Name = "Kola",
                            ShopId = 1
                        },
                        new
                        {
                            Id = 2,
                            ExpiryDate = new DateTime(2021, 12, 23, 17, 0, 20, 306, DateTimeKind.Utc).AddTicks(7996),
                            Name = "Bulka",
                            ShopId = 2
                        },
                        new
                        {
                            Id = 3,
                            ExpiryDate = new DateTime(2021, 12, 23, 17, 0, 20, 306, DateTimeKind.Utc).AddTicks(7998),
                            Name = "Sviestas",
                            ShopId = 1
                        },
                        new
                        {
                            Id = 4,
                            ExpiryDate = new DateTime(2021, 12, 23, 17, 0, 20, 306, DateTimeKind.Utc).AddTicks(7999),
                            Name = "Grietinė",
                            ShopId = 1
                        });
                });

            modelBuilder.Entity("EfCoreShop.Models.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tags");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Pirmas"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Antras"
                        });
                });

            modelBuilder.Entity("EfCoreShop.Models.ShopItemTag", b =>
                {
                    b.HasOne("EfCoreShop.Models.Shopitem", "Shopitem")
                        .WithMany("ShopItemTags")
                        .HasForeignKey("ShopItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EfCoreShop.Models.Tag", "Tag")
                        .WithMany("ShopItemTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shopitem");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("EfCoreShop.Models.Shopitem", b =>
                {
                    b.HasOne("EfCoreShop.Models.Shop", "Shop")
                        .WithMany()
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shop");
                });

            modelBuilder.Entity("EfCoreShop.Models.Shopitem", b =>
                {
                    b.Navigation("ShopItemTags");
                });

            modelBuilder.Entity("EfCoreShop.Models.Tag", b =>
                {
                    b.Navigation("ShopItemTags");
                });
#pragma warning restore 612, 618
        }
    }
}
